test stage

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -31,7 +31,25 @@ stages:
         targetPath: '$(Pipeline.Workspace)/s/kubernetes'
         artifact: 'manifests'
         publishLocation: 'pipeline'
-
+- stage: test
+  displayName: 'Test'
+  jobs:
+  - job: test
+    displayName: 'Test API'
+    steps:
+    - script: |
+        curl http://localhost:5000/check_api
+      displayName: 'Send API test request'
+    - script: |
+        if [ "$?" -eq 0 ]
+        then
+          echo "API test succeeded"
+          exit 0
+        else
+          echo "API test failed"
+          exit 1
+        fi
+      displayName: 'Check API test response'
 - stage: Deploy
   displayName: Deploy to Dev
   dependsOn: Build
